FROM python:3

ARG MYAPP MYUID

ENV MYAPP=$MYAPP

COPY tools .

RUN pip install -r requirements.txt

RUN chmod +x entrypoint.sh

RUN addgroup --gid $MYUID --system $MYAPP;

RUN adduser --uid $MYUID --system --disabled-password --ingroup $MYAPP \
--no-create-home --home /usr/src/app --shell /bin/bash $MYAPP;

WORKDIR /usr/src/app

RUN chown -R $MYAPP:$MYAPP .;

RUN chown $MYAPP:$MYAPP /entrypoint.sh;

USER $MYAPP

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# CMD ["sleep", "infinity"]